- name : delete the app directory if exists
  ansible.builtin.file: 
    path : "{{ app_location }}"
    state : absent

- name : create app directory
  ansible.builtin.file:
    path : "{{ app_location }}"
    state : directory

# - name : download and extract the code
#   ansible.builtin.unarchive:
#     src : "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
#     dest : "{{ app_location }}"
#     remote_src : yes

# - name : download code from nexus
#   ansible.builtin.unarchive:
#     src : "http://nexus.chandradevops.online:8081/repository/backend/com/expense/backend/{{ AppVersion }}/backend-{{ AppVersion }}.zip"
#     dest : "{{ app_location }}"
#     remote_src : yes


- name: Download backend artifact from Nexus
  ansible.builtin.get_url:
    url: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ AppVersion }}/{{ component }}-{{ AppVersion }}.zip"
    dest: "/tmp/{{ component }}-{{ AppVersion }}.zip"
    url_username: "{{ login_user }}"
    url_password: "{{ login_password }}"
    force: yes
    mode: '0644'

- name: Extract backend artifact
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}-{{ AppVersion }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes
